### PR TITLE
Make the cassette player attachable to walls

### PR DESCRIPTION
**Pull request by SnubbyNotSorry**
These are changes that make the cassette player attachable to walls on top of its current functions. You could also opt to make the attachable version its own item. Includes a rough sprite for the attached version, and code documentation on (I believe) every change or addition I've made to the .xml ! Feel free to contact me on Steam or from the Baro Discord if needed.

I'm rusty with Git so I hope I did this properly ! And sorry I don't seem to have you .xml formatting, heh..

### CODE REVIEW

**Comment by Garnet-san** [comment]
I took a look at the code but realized I don't really remember much. So instead I downloaded and booted Barotrauma loaded RIMM with your changes and went into editor to try it.
There are three small "issues" I have. Nothing big but I think it would be nice to have those adjusted before we publish it on steam workshop.
My issues:
1. Inconsistency with vanilla attachable items. Vanilla attachable items (AND, OR and other logic circuits) are attached to walls after pressing left mouse button, while with cassette player I had to press E on keyboard to attach it. I think it would be nice to make it work in same way as vanilla items do.
2. Light source is too large, and out of place when cassette player is on.
3. There is no need for different sprite for cassette-player. Unless we make it separate item, which I don't is necessary, we can just keep it as it is. Therefore changes to CassettePlayer.png are not necessary.

Overall I am pleased with this addition if we get those small "issues", mentioned above, resolved.
This idea also got me thinking that we could make cassette player battery powered, it would make sense to do so.

**Comment by Mylapqn** [comment]
Agreed, the behaviour should be the same as vanilla attachables. Also agree on the sprite, existing one is fine as is unless we wanna make the attachable larger or something. Which isn't necessary in my opinion.

Once these are sorted, I think it'll be a great addition to the base mod!

Also forgot to mention, thanks for the comprehensive commenting in the file! Really helpful ^^

**Comment by SnubbyNotSorry** [comment]
Bear with me, too lazy to figure out how to Merge probably again x)

Anyway ! All three of your requests have been taken into account, and I think the mod looks good now ! The only hiccup is that the light is on when the cassette player is attached and ON but not when it plays in hand/on the floor, and I frankly don't know if there is a way to make the same light component handle both cases. I could make a second light component for that, but then in the wiring panel both would show and have different colours and eeeeeeehh, personally, I think that would be confused. You tell me ! I'll try and get it working the way I want to if I feel brave later.

**Comment by Garnet-san** [comment]
Did quick in-game testing and I am all in for merge. My complains were resolved and now it looks perfect!

**Comment by Mylapqn** [comment]
Alright, all good by me too then! I'm merging it, thanks for your great work!

**Pull request merged**
